-- Solicitação (tabela base de toda solicitação feita ao assistente; cada tipo tem sua tabela de detalhe)
CREATE TABLE requests (
    id         bigint generated by default as identity primary key,
    type       varchar(30) NOT NULL,
    status     varchar(20) NOT NULL DEFAULT 'PENDING',
    created_by bigint NOT NULL,
    created_at timestamp(6) NOT NULL
);

-- Sala de reunião (cadastro simples; a IA usa isso pra saber o que existe pra sugerir)
CREATE TABLE rooms (
    id        bigint generated by default as identity primary key,
    name      varchar(200) NOT NULL,
    capacity  int NOT NULL,
    location  varchar(200) NULL,
    equipment varchar(500) NULL,
    active    bool NOT NULL DEFAULT true,
    CONSTRAINT rooms_name_key UNIQUE (name)
);

-- Reserva de sala de reunião (detalhe de uma solicitação do tipo ROOM_BOOKING)
CREATE TABLE room_booking_requests (
    id              bigint generated by default as identity primary key,
    request_id      bigint NOT NULL UNIQUE,
    room_id         bigint NOT NULL,
    booking_date    date NOT NULL,
    start_time      time NOT NULL,
    end_time        time NOT NULL,
    attendees_count int NULL,
    purpose         varchar(300) NULL,
    CONSTRAINT fk_room_booking_request_request FOREIGN KEY (request_id) REFERENCES requests(id),
    CONSTRAINT fk_room_booking_request_room FOREIGN KEY (room_id) REFERENCES rooms(id)
);

CREATE INDEX idx_room_booking_request_room_date ON room_booking_requests (room_id, booking_date);
